alias cbash="code ~/.bashrc"
alias czsh="code ~/.zshrc"
alias n10='nvm use 10'
alias n14='nvm use 14'
alias ni10="nvm exec 10 npm i"
alias node10="nvm exec 10 node app.js"
alias npmrc="npm run start-remote"
alias npmr="npm run start"
alias cals="code ~/myscripts/alias.sh"
alias cgit="code  ~/myscripts/git.sh"
alias cpm="code  ~/myscripts/pm.sh"
alias stopredis="sudo service redis-server stop"
alias avc1='bash /Users/utkarsh/aws_ec2_connect.sh ap-south-1'
alias avc2='bash /Users/utkarsh/aws_ec2_connect.sh ap-south-2'
alias myzoom='open "zoommtg://zoom.us/join?confno=4509936030?pwd=Um5CRmx4OURJWENiTzA4bmphMkxRZz09"'
alias stopredisM="sudo service redis-server stop --port 9996"
alias bm="npm run build --prefix ~/work/Mondayne"
alias sm="npm start --prefix ~/work/Mondayne"
alias apc='cd ~/work/data-nimbus/main/dnio-ui-appcenter'
alias aut='cd ~/work/data-nimbus/main/dnio-ui-author'
alias ngs='ng serve'
alias ds='cd ~/work/data-nimbus'
alias dsd='cd ~/work/data-nimbus/deploy'
alias syncall='cd ~/work/data-nimbus/deploy;./sync.sh'
alias cenv='code ~/myscripts/env.sh'
alias cscr='code ~/myscripts/scripts.sh'
alias google="web_search google"
alias be='cd ~/work/data-nimbus/main'
alias pelis='startfe; startbe'
alias mys='cd ~/myscripts'
alias checkjen='node ~/work/data-nimbus/jenkins-project/jenkins.js'
alias newhope='nc towel.blinkenlights.nl 23'
alias cbf='ssh -i ~/dn.pem ubuntu@35.154.243.231'
alias be9='cd ~/work/data-nimbus/v29'
alias be8='cd ~/work/data-nimbus/v28'
alias bem='cd ~/work/data-nimbus/main'
alias npmli='npm i --legacy-peer-deps'
alias pmw='node ~/work/data-nimbus/pm2-webui/app.js >/dev/null'
alias aut9='cd ~/work/data-nimbus/v29/dnio-ui-author'
alias apc9='cd ~/work/data-nimbus/v29/dnio-ui-appcenter'
alias aut8='cd ~/work/data-nimbus/v28/dnio-ui-author'
alias apc8='cd ~/work/data-nimbus/v28/dnio-ui-appcenter'
alias casp='code /Users/utkarsh/Library/"Application Support"/espanso/match/base.yml'
alias bld='node ~/work/data-nimbus/jenkins-project/build.js'
alias ech='open "https://ap-south-2.console.aws.amazon.com/ec2/home?region=ap-south-2#Instances:v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false"'
alias ecm='open "https://ap-south-2.console.aws.amazon.com/ec2/home?region=ap-south-1#Instances:v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false"'
