alias cbash="code ~/.bashrc"
alias czsh="code ~/.zshrc"
alias n10='nvm use 10'
alias n14='nvm use 14'
alias ni10="nvm exec 10 npm i"
alias node10="nvm exec 10 node app.js"
alias npmrc="npm run start-remote"
alias npmr="npm run start"
alias cals="code ~/myscripts/alias.sh"
alias cgit="code  ~/myscripts/git.sh"
alias stopredis="sudo service redis-server stop"
alias avc='cd ~;./avconnect-macos -r;cd -'
alias myzoom='open "zoommtg://zoom.us/join?confno=4509936030?pwd=Um5CRmx4OURJWENiTzA4bmphMkxRZz09"'
alias stopredisM="sudo service redis-server stop --port 9996"
alias bm="npm run build --prefix ~/work/Mondayne"
alias sm="npm start --prefix ~/work/Mondayne"
alias apc='cd ~/work/data-nimbus/frontend/dnio-ui-appcenter'
alias aut='cd ~/work/data-nimbus/frontend/dnio-ui-author'
alias ngs='ng serve'
alias ds='cd ~/work/data-nimbus'
alias dsfe='cd ~/work/data-nimbus/frontend'
alias dsbe='cd ~/work/data-nimbus/backend'
alias dsd='cd ~/work/data-nimbus/deploy'
alias syncall='cd ~/work/data-nimbus/deploy;./sync.sh'
alias cenv='code ~/myscripts/env.sh'
alias cscr='code ~/myscripts/scripts.sh'
alias google="web_search google"
alias be='cd ~/work/data-nimbus/backend'
alias pelis='startfe; startbe'
alias mys='cd ~/myscripts'
alias checkjen='node ~/work/data-nimbus/jenkins-project/jenkins.js'
